### ISSUE TITLE
Use some form of "templating"

### ISSUE THREAD

**Issue by nitori** [laper26/Solve-IT-yourself#20]
To avoid duplicate HTML code, it's probably reasonable to use some form of simple templating engine. Currently `config.php` and `index.php` have pretty much the same content.

**Comment by AnsPunktF** [comment]
maybe we sould split the current index.php and add a header.php and footer.php

**Comment by nitori** [comment]
AFAIK we're getting some cheap templating thingy. So it's probably best to wait for now.
